export var inputDados = [
  {
    type: "text",
    id: "name",
    name: "name",
    placeholder: "Name",
    value: "Name",
    rowClass: "",
    labelClass: "",
    options: [],
    required: true,
  },
  {
    type: "text",
    id: "cartaoCredito",
    name: "cartaoCredito",
    value: "Cartao",
    placeholder: "Numero do Cartao",
    rowClass: "",
    labelClass: "",
    options: [],
    required: true,
  },
  {
    type: "text",
    id: "cpf",
    name: "cpf",
    placeholder: "CPF",
    value: "CPF",
    rowClass: "",
    labelClass: "",
    options: [],
    required: true,
  },
  {
    type: "text",
    id: "cep",
    name: "cep",
    placeholder: "00000-000",
    value: "CEP",
    rowClass: "",
    labelClass: "",
    options: [],
    required: true,
  },
  {
    type: "text",
    id: "address",
    name: "address",
    placeholder: "Street, Avenue, etc...",
    value: "Address",
    rowClass: "",
    labelClass: "",
    options: [],
    required: true,
  },
  {
    type: "textarea",
    id: "text-area",
    name: "text-area",
    placeholder: "Text...",
    value: "Text Area",
    rowClass: "",
    labelClass: "",
    options: [],
    required: false,
  },
  {
    type: "dropdown",
    id: "drop-down",
    name: "drop-down",
    placeholder: "",
    value: "Drop Down",
    rowClass: "drop-down",
    labelClass: "",
    options: ["Meu peao nao quer", "agora sim nos vamos", "subir contra"],
    required: false,
  },
  {
    type: "file",
    id: "file-upload",
    name: "file-upload",
    placeholder: "",
    value: "Choose file",
    rowClass: "file-upload-div",
    labelClass: "file-upload-label",
    options: [],
    required: true,
  },
  {
    type: "radio",
    id: "",
    name: "",
    placeholder: "",
    value: "Radio Options",
    rowClass: "radio-div",
    labelClass: "",
    options: [
      { id: "radio-input-1", name: "radio-input", value: "radio-input-1" },
      { id: "radio-input-2", name: "radio-input", value: "radio-input-2" },
      { id: "radio-input-3", name: "radio-input", value: "radio-input-3" },
      { id: "radio-input-4", name: "radio-input", value: "XABLAU" },
      { id: "radio-input-5", name: "radio-input", value: "MOSKAA" },
    ],
    required: true,
  },
  {
    type: "checkbox",
    id: "",
    name: "",
    placeholder: "",
    value: "Checkbox Options",
    rowClass: "checkbox-div",
    labelClass: "",
    options: [
      { id: "checkbox-input-1", name: "checkbox-input-1", value: "checkbox-input-1" },
      { id: "checkbox-input-2", name: "checkbox-input-2", value: "checkbox-input-2" },
      { id: "checkbox-input-3", name: "checkbox-input-3", value: "checkbox-input-3 a a aa" },
      { id: "checkbox-input-4", name: "checkbox-input-4", value: "XABLAU      aaaaa" },
      { id: "checkbox-input-5", name: "checkbox-input-5", value: "MOSKAA" },
    ],
    required: true,
  },
];
